#!/usr/local/bin/m_venv3/bin/python
import fire

from m_docker import Docker
from m_deploy import Deploy
from m_chef import Chef
from m_www import WWW
from m_keras import Keras

from m_audio import Audio


class M2:
    def __init__(self):
        self.docker = Docker()
        self.chef = Chef()
        self.deploy = Deploy()
        self.www = WWW()
        self.keras = Keras()

        self.audio = Audio()

    def debug(self):
        print('TBD')


if __name__ == '__main__':
    fire.Fire(M2())
