#!/usr/local/bin/m_venv/bin/python

import argparse
import os
import shutil
import subprocess
import yaml

parser = argparse.ArgumentParser()
parser.add_argument('cmd')
parser.add_argument('--tag', help='for building docker img')
parser.add_argument('--role', help='for reheating')

args = parser.parse_args()

HOME = os.path.expanduser('~')
ROOT = os.path.expanduser('~/dev')
SSH_DIR = os.path.expanduser('~/.ssh')

M_ROOT = os.path.dirname(os.path.realpath(__file__))

def path(folder):
    return os.path.join(ROOT, folder)

if args.cmd == 'build':
    config_yml = {}
    if os.path.isfile('./config.yml'):
        with open('./config.yml') as f:
            config_yml = yaml.load(f)

    remove_after = ['./gitlab_rsa', './.dockerignore']

    if config_yml.get('resolve'):
        for src, dst in config_yml.get('resolve').items():
            shutil.copy2(src, dst)
            remove_after.append(dst)

    # Copy gitlab cert
    shutil.copy2(os.path.join(SSH_DIR, 'key', 'gitlab_rsa'), './gitlab_rsa')
    # Copy over dockerignore
    shutil.copy2(os.path.join(M_ROOT, '.dockerignore'), './.dockerignore')

    tag = args.tag
    p = subprocess.Popen('docker build . -t %s' % tag, shell=True)
    p.communicate()

    subprocess.check_output('docker save %s | gzip -c > ~/dev/chub/%s.gz' % (tag, tag), shell=True)
    [os.remove(f) for f in remove_after]

    cmd = 'cd %s && git add . && git ci -m updated %s.gz && git push origin master' % (path('chub'), tag)
    p = subprocess.Popen(cmd, shell=True)
    p.communicate()

elif args.cmd == 'deploy':
    app = args.tag

    # first run deploy_assets
    if app == 'slothapp':
        cmd = 'cd %s && ./deploy_asset.sh' % path('dotfiles/m/ops/%s' % app)
        p = subprocess.Popen(cmd, shell=True)
        p.communicate()

    p = subprocess.Popen('cd %s && ./deploy.sh %s' % (path('dotfiles/m/ops'), app), shell=True)
    p.communicate()

elif args.cmd == 'ginit':
    gitignore = args.tag
    gitignore[0] = gitignore[0].upper()

    p = subprocess.Popen('ginit %s' % gitignore, shell=True)
    p.communicate()

elif args.cmd == 'reheat':
    role = args.role

    # cp chef folder to ~/.chef
    chef_run_dir = os.path.expanduser('~/.chef')

    if not os.path.exists(chef_run_dir):
        os.mkdir(chef_run_dir)

    # copy over chef
    print(path('dotfiles/chef'), chef_run_dir)

    p = subprocess.Popen('cp -r %s/* %s' % (path('dotfiles/chef'), chef_run_dir), shell=True)
    p.communicate()

    # run bash install.sh' "$role"
    p = subprocess.Popen('cd %s && sudo bash install.sh %s' % (chef_run_dir, role), shell=True)
    p.communicate()

elif args.cmd == 'mmv':
    # TODO: implement an easy way to mass rename files
    pass

elif args.cmd == 'dload':
    app = args.tag
    p = subprocess.Popen('docker load < %s.gz' % (app, app), shell=True)
    p.communicate()
