FROM rust:1.58.0 AS build-env

ARG APPDIR
ARG APP

WORKDIR /app
COPY $APPDIR /app
RUN cargo build --release -p $APP

FROM gcr.io/distroless/cc

COPY --from=build-env /app/target/release/$APP /app
CMD ["/app"]
