FROM rust:1.73.0-bullseye AS build-env

ARG APPDIR
ARG APP

RUN apt update && apt install -y protobuf-compiler

WORKDIR /app
COPY $APPDIR /app
RUN rustup component add rustfmt && cargo build --release -p $APP

FROM gcr.io/distroless/cc
ARG APP

COPY --from=build-env /app/target/release/$APP /app
CMD ["/app"]
