FROM golang:1.18-stretch as build-env

ARG APP
# src directory must be of form `go/src/<GOMOD>`
ARG GOMOD
ARG TAGS=""

# build-env has `/go` by default
WORKDIR /
ADD go/src/$GOMOD go/src/$GOMOD

WORKDIR /go/src/$GOMOD
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download -x
RUN go build $TAGS -o /go/bin/app $GOMOD/cmd/$APP

FROM gcr.io/distroless/base
COPY --from=build-env /go/bin/app /app
CMD ["/app"]
