#!/usr/bin/env python

import argparse
import os
import shutil
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("cmd")
parser.add_argument("tag")

args = parser.parse_args()

if args.cmd == 'build':
    tag = args.tag
    shutil.copy2('/Users/moomou/.ssh/gitlab_rsa', './gitlab_rsa')
    p = subprocess.Popen('docker build . -t %s' % tag, shell=True)
    p.communicate()

    subprocess.check_output('docker save %s | gzip -c > ~/dev/chub/%s.gz' % (tag, tag), shell=True)
    os.remove('./gitlab_rsa')
elif args.cmd == "deploy":
    app = args.tag
    p = subprocess.Popen('cd /Users/moomou/dev/_prod/%s && ./deploy.sh' % app, shell=True)
    p.communicate()

